services:
  app:
    build: .
    container_name: inventario_app
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: inventario_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: inventorio_v9
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: inventario_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: