; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Inventario v9"
#define MyAppVersion "9.0"
#define MyAppPublisher "Mi Empresa"
#define MyAppURL "http://www.example.com/"
#define MyAppExeName "phpdesktop-chrome.exe"

[Setup]
AppId={{32AB5AB0-B090-4962-B5B4-894CBAC85205}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputDir=D:\Inventario-v9-Instalador
OutputBaseFilename=Inventario-v9-Setup
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; === Archivos principales de phpdesktop ===
Source: "D:\Inventario-v9\phpdesktop-chrome.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Inventario-v9\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; === FORZAR INCLUSIÓN DEL PHP.INI CON EXTENSIÓN INTL ===
Source: "D:\Inventario-v9\php\php.ini"; DestDir: "{app}\php"; Flags: ignoreversion

; === Tu aplicación Laravel ===
Source: "D:\Inventario-v9\www\Inventario-v9\*"; DestDir: "{app}\www\Inventario-v9"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent